# AutonomousVehiclePerception/deploy/docker/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["django:8000"]

  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi:8001"]

  - job_name: "triton"
    static_configs:
      - targets: ["triton:8002"]
    metrics_path: /metrics
